export const QUESTION_TYPE = {
  PRONOUNCE_1_WORD_FROM_TEXT: 'PRONOUNCE_1_WORD_FROM_TEXT',
  TYPE_1: 'MULTIPLE_CHOICE_TYPE_1',
  TYPE_7: 'MULTIPLE_CHOICE_TYPE_7',
  TYPE_8: 'MULTIPLE_CHOICE_TYPE_8',
}
